/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongoinsert;

import org.bson.Document;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Replace the uri string with your MongoDB deployment's connection string
        String uri = "mongodb://oklab:oklab_2023@110.13.86.60:60001/";

        MongoClient mongoClient = MongoClients.create(uri);

        MongoDatabase database = mongoClient.getDatabase("fire-detection");
        MongoCollection<Document> collection = database.getCollection("test");

        Document doc = new Document("name", "MongoDB")
                 .append("type", "database")
                 .append("count", 1);

        collection.insertOne(doc);
    }
}
